### ISSUE TITLE
`stat_visualization merge`コマンドのエラーを解決する

### ISSUE THREAD

**Issue by yuji38kwmt** [kurusugawa-computer/annofab-cli#1128]
```
WARNING  : 2024-02-08 01:21:55,882 : annofabcli.common.utils        : can't serialize <class 'pandas._libs.missing.NAType'>
ERROR    : 2024-02-08 01:21:55,883 : annofabcli.common.utils        : can't serialize <class 'pandas._libs.missing.NAType'>
Traceback (most recent call last):
  File "/home/yuji/.pyenv/versions/3.12.1/lib/python3.12/site-packages/annofabcli/common/utils.py", line 286, in wrapped
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuji/.pyenv/versions/3.12.1/lib/python3.12/site-packages/annofabcli/stat_visualization/merge_visualization_dir.py", line 63, in execute_merge_performance_per_user
    output_project_dir.write_user_performance_scatter_plot(merged_user_performance)
  File "/home/yuji/.pyenv/versions/3.12.1/lib/python3.12/site-packages/annofabcli/statistics/visualization/project_dir.py", line 244, in write_user_performance_scatter_plot
    obj.plot_quality(output_dir / "散布図-教師付者の品質と作業量の関係.html")
  File "/home/yuji/.pyenv/versions/3.12.1/lib/python3.12/site-packages/annofabcli/statistics/visualization/dataframe/user_performance.py", line 868, in plot_quality
    write_bokeh_graph(bokeh.layouts.column([div_element, *figure_list]), output_file)
  File "/home/yuji/.pyenv/versions/3.12.1/lib/python3.12/site-packages/annofabcli/statistics/scatter.py", line 22, in write_bokeh_graph
    bokeh.plotting.save(bokeh_obj)
  File "/home/yuji/.pyenv/versions/3.12.1/lib/python3.12/site-packages/bokeh/io/saving.py", line 98, in save
    _save_helper(obj, filename, resources, title, template, theme)
  File "/home/yuji/.pyenv/versions/3.12.1/lib/python3.12/site-packages/bokeh/io/saving.py", line 164, in _save_helper
    html = file_html(obj, resources, title=title, template=template or FILE, theme=theme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuji/.pyenv/versions/3.12.1/lib/python3.12/site-packages/bokeh/embed/standalone.py", line 357, in file_html
    (docs_json, render_items) = standalone_docs_json_and_render_items(models_seq, suppress_callback_warning=suppress_callback_warning)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuji/.pyenv/versions/3.12.1/lib/python3.12/site-packages/bokeh/embed/util.py", line 330, in standalone_docs_json_and_render_items
    docs_json[docid] = doc.to_json(deferred=False)
```

bokeh をバージョンアップすれば解決するが、Python3.8をサポートしているためそれはできない。

**Comment by yuji38kwmt** [comment]
`pandas.NA`を含まないようにして対応した
